# Generated by Django 4.2.6 on 2023-11-02 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_items_item_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='item_img',
        ),
    ]
