# Generated by Django 4.2.6 on 2023-11-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_remove_items_item_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_img',
            field=models.ImageField(default=None, upload_to='static\\images'),
        ),
    ]
