# Generated by Django 4.2.6 on 2023-11-08 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookings',
        ),
    ]
