# Generated by Django 4.2.6 on 2023-11-08 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='total_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
