# Generated by Django 4.2.6 on 2023-11-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_bookings_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_status',
            field=models.BooleanField(),
        ),
    ]
