# Generated by Django 4.2.6 on 2023-11-08 03:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0011_alter_items_item_img'),
        ('bookings', '0005_alter_bookings_booking_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookings',
            new_name='Bookorders',
        ),
    ]
